environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable

matrix:
  allow_failures:
    - CHANNEL: nightly

cache:
  - C:\Users\appveyor\.cargo

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-toolchain %CHANNEL% --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build
  
build_success:
  - rmdir /s /q C:\Users\appveyor\.cargo\registry
